name: Apollo CI Mystery

on:
  push:
    branches-ignore: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

  launch:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo "L" > token.txt
      - uses: actions/upload-artifact@v4
        with:
          name: token1
          path: token.txt

  transposition_and_docking:
    needs: launch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: token1
      - run: echo "U" >> token.txt
      - uses: actions/upload-artifact@v4
        with:
          name: token2
          path: token.txt

  lunar_orbit_insertion:
    needs: transposition_and_docking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: token2         
      - run: echo "N" >> token.txt
      - uses: actions/upload-artifact@v4
        with:
          name: token3          
          path: token.txt

  splashdown:
    needs: lunar_orbit_insertion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/download-artifact@v4
        with:
          name: token3

      - name: âœ… Verifica token y muestra mensaje lunar
        run: |
          ACTUAL=$(tr -d '\n' < token.txt)
          if [[ "$ACTUAL" == "LUN" ]]; then
            echo "ðŸŒŠ 4) Splashdown completado"
            python apollo/mission.py
          else
            echo "âŒ Secuencia incorrecta. Token='$ACTUAL', esperado='LUN'"
            exit 1
          fi
